#pragma once
#include <qglobal.h>
#include <QMap>

//
// The .NET performance counters, as values.
//
// The CLR publishes these through an IPC block that only a local, native
// collector can read; what crosses the boundary - to the GUI today, over the
// wire later - is the number and how to render it, never the rendered text.
// The labels live with the tree that shows them, in GUI/TaskInfo.
//
// Index values are the vocabulary both sides share, so they are part of the
// protocol: append, never renumber.
//

enum EDotNetCounter
{
    // .NET CLR Exceptions (Runtime statistics on CLR exception handling)
    DOTNET_CATEGORY_EXCEPTIONS,
    // .NET CLR Interop (Stats for CLR interop)
    DOTNET_CATEGORY_INTEROP,
    // .NET CLR Jit (Stats for CLR Jit)
    DOTNET_CATEGORY_JIT,
    // .NET CLR Loading (Statistics for CLR Class Loader)
    DOTNET_CATEGORY_LOADING,
    // .NET CLR LocksAndThreads (Stats for CLR Locks and Threads)
    DOTNET_CATEGORY_LOCKSANDTHREADS,
    // .NET CLR Memory (Counters for CLR Garbage Collected heap)
    DOTNET_CATEGORY_MEMORY,
    // .NET CLR Remoting (Stats for CLR Remoting)
    DOTNET_CATEGORY_REMOTING,
    // .NET CLR Security (Stats for CLR Security)
    DOTNET_CATEGORY_SECURITY,

	// 
    DOTNET_INDEX_EXCEPTIONS_THROWNCOUNT,
    DOTNET_INDEX_EXCEPTIONS_FILTERSCOUNT,
    DOTNET_INDEX_EXCEPTIONS_FINALLYCOUNT,

    DOTNET_INDEX_INTEROP_CCWCOUNT,
    DOTNET_INDEX_INTEROP_STUBCOUNT,
    DOTNET_INDEX_INTEROP_MARSHALCOUNT,
    DOTNET_INDEX_INTEROP_TLBIMPORTPERSEC,
    DOTNET_INDEX_INTEROP_TLBEXPORTPERSEC,

    DOTNET_INDEX_JIT_ILMETHODSJITTED,
    DOTNET_INDEX_JIT_ILBYTESJITTED,
    DOTNET_INDEX_JIT_ILTOTALBYTESJITTED,
    DOTNET_INDEX_JIT_FAILURES,
    DOTNET_INDEX_JIT_TIME,

    DOTNET_INDEX_LOADING_CURRENTLOADED,
    DOTNET_INDEX_LOADING_TOTALLOADED,
    DOTNET_INDEX_LOADING_CURRENTAPPDOMAINS,
    DOTNET_INDEX_LOADING_TOTALAPPDOMAINS,
    DOTNET_INDEX_LOADING_CURRENTASSEMBLIES,
    DOTNET_INDEX_LOADING_TOTALASSEMBLIES,
    DOTNET_INDEX_LOADING_ASSEMBLYSEARCHLENGTH,
    DOTNET_INDEX_LOADING_TOTALLOADFAILURES,
    DOTNET_INDEX_LOADING_BYTESINLOADERHEAP,
    DOTNET_INDEX_LOADING_TOTALAPPDOMAINSUNLOADED,

    DOTNET_INDEX_LOCKSANDTHREADS_TOTALLOCKS,
    DOTNET_INDEX_LOCKSANDTHREADS_TOTALQUEUELENGTH,
    DOTNET_INDEX_LOCKSANDTHREADS_QUEUELENGTHPEAK,
    DOTNET_INDEX_LOCKSANDTHREADS_CURRENTLOGICAL,
    DOTNET_INDEX_LOCKSANDTHREADS_CURRENTPHYSICAL,
    DOTNET_INDEX_LOCKSANDTHREADS_CURRENTRECOGNIZED,
    DOTNET_INDEX_LOCKSANDTHREADS_TOTALRECOGNIZED,

    DOTNET_INDEX_MEMORY_GENZEROCOLLECTIONS,
    DOTNET_INDEX_MEMORY_GENONECOLLECTIONS,
    DOTNET_INDEX_MEMORY_GENTWOCOLLECTIONS,
    DOTNET_INDEX_MEMORY_PROMOTEDFROMGENZERO,
    DOTNET_INDEX_MEMORY_PROMOTEDFROMGENONE,
    DOTNET_INDEX_MEMORY_PROMOTEDFINALFROMGENZERO,
    DOTNET_INDEX_MEMORY_PROCESSID,
    DOTNET_INDEX_MEMORY_GENZEROHEAPSIZE,
    DOTNET_INDEX_MEMORY_GENONEHEAPSIZE,
    DOTNET_INDEX_MEMORY_GENTWOHEAPSIZE,
    DOTNET_INDEX_MEMORY_LOHSIZE,
    DOTNET_INDEX_MEMORY_FINALSURVIVORS,
    DOTNET_INDEX_MEMORY_GCHANDLES,
    DOTNET_INDEX_MEMORY_INDUCEDGC,
    DOTNET_INDEX_MEMORY_TIMEINGC,
    DOTNET_INDEX_MEMORY_BYTESINALLHEAPS,
    DOTNET_INDEX_MEMORY_TOTALCOMMITTED,
    DOTNET_INDEX_MEMORY_TOTALRESERVED,
    DOTNET_INDEX_MEMORY_TOTALPINNED,
    DOTNET_INDEX_MEMORY_TOTALSINKS,
    DOTNET_INDEX_MEMORY_TOTALBYTESSINCESTART,
    DOTNET_INDEX_MEMORY_TOTALLOHBYTESSINCESTART,

    DOTNET_INDEX_REMOTING_TOTALREMOTECALLS,
    DOTNET_INDEX_REMOTING_CHANNELS,
    DOTNET_INDEX_REMOTING_CONTEXTPROXIES,
    DOTNET_INDEX_REMOTING_CONTEXTCLASSESLOADED,
    DOTNET_INDEX_REMOTING_CONTEXTS,
    DOTNET_INDEX_REMOTING_CONTEXTSALLOCATED,

    DOTNET_INDEX_SECURITY_TOTALRUNTIMECHECKS,
    DOTNET_INDEX_SECURITY_LINKTIMECHECKS,
    DOTNET_INDEX_SECURITY_TIMEINRTCHECKS,
    DOTNET_INDEX_SECURITY_STACKWALKDEPTH,

    DOTNET_INDEX_MAXIMUM
};

struct SDotNetCounter
{
	enum EFormat
	{
		eCount,		// a quantity - grouped digits
		ePlain,		// a quantity that is not really a count (a pid) - no grouping
		eSize,		// a byte count
		ePercent,	// a ratio, already scaled to 0..100
	};

	SDotNetCounter() : Format(eCount), Value(0), Ratio(0.0f) {}
	SDotNetCounter(EFormat F, quint64 V) : Format(F), Value(V), Ratio(0.0f) {}
	SDotNetCounter(float R) : Format(ePercent), Value(0), Ratio(R) {}

	EFormat		Format;
	quint64		Value;
	float		Ratio;
};

typedef QMap<int, SDotNetCounter> SDotNetCounters;
